name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Integração contínua
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://sergiojr:sergiojr@postgres:5432/sergiojr

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: sergiojr
          POSTGRES_USER: sergiojr
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5



    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10.6
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup .env
      run: cp .env.example .env

    - name: Lint with flake8
      run: |          
      # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide          
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests
      run: |
        export ALLOWED_HOSTS="${{ secrets.ALLOWED_HOSTS }}"
        python manage.py test
        

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: ci

    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only